# Week-5

NLP-Fundamentals

# DAY-1

What is NLP?
Applications of NLP
Text data & language understanding
NLP workflow(collect text data,clean it, tokenize it,convert into num,ML)
Text preprocessing basics
Tokenization
Words / sentences split concept


 # Day-2

Text lowercase to uppercase

In [1]:
text = "WOW!!! I LOVE This Movie 😍"

clean_text = text.lower()

print(clean_text)

wow!!! i love this movie 😍


Punctuation Removal

In [2]:
import string

text = "WOW!!! I LOVE This Movie 😍"

clean_text = text.lower()
clean_text = clean_text.translate(str.maketrans("", "", string.punctuation))

print(clean_text)

wow i love this movie 😍


Extra spaces & unwanted characters cleaning

In [3]:
text = "I    love     this    movie"

clean_text = " ".join(text.split())

print(clean_text)

I love this movie


In [4]:
pip install nltk

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 629.9 kB/s eta 0:00:03
   ----------- ---------------------------- 0.5/1.8 MB 629.9 kB/s eta 0:00:03
   ----------------- ---------------------- 0.8/1.8 MB 706.7 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 747.4 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 747.4 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 793.2 kB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 814.0 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 802.5 kB/s  0:00:02

   ------------------------------

Stop Words

In [5]:
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

text = "The movie is very good"

words = text.lower().split()

stop_words = set(stopwords.words("english"))

filtered_words = [word for word in words if word not in stop_words]

print(filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


['movie', 'good']


[nltk_data]   Unzipping corpora\stopwords.zip.


Stemming (Fast+Simple)

playing  → play
played   → play
plays    → play

Lemmmatization(More accurate+Meaning-based)

running → run
better  → good
children → child





In [6]:
import string

text = "WOW!!!   I LOVE This Movie 😍"

# 1. Lowercase
text = text.lower()

# 2. Remove punctuation
text = text.translate(str.maketrans("", "", string.punctuation))

# 3. Remove extra spaces
text = " ".join(text.split())

print(text)

wow i love this movie 😍


# day-3

Tokenization

In [14]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

text = "I love AI"

words = word_tokenize(text)

print(words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['I', 'love', 'AI']


In [15]:
import nltk
from nltk.tokenize import sent_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

text = "I love AI. NLP is interesting. I am learning NLP."

sentences = sent_tokenize(text)

print(sentences)

['I love AI.', 'NLP is interesting.', 'I am learning NLP.']


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [16]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

text = "The movie is very good and I love it"

words = word_tokenize(text.lower())

stop_words = set(stopwords.words("english"))

filtered_words = [
    word for word in words
    if word not in stop_words
]

print("Original:", words)
print("After stop words removal:", filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


Original: ['the', 'movie', 'is', 'very', 'good', 'and', 'i', 'love', 'it']
After stop words removal: ['movie', 'good', 'love']


[nltk_data]   Package punkt_tab is already up-to-date!


In [17]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")

text = "I love learning NLP because it is very interesting"

# Step 1: Convert to lowercase
text = text.lower()

# Step 2: Tokenization
words = word_tokenize(text)

# Step 3: Get English stop words
stop_words = set(stopwords.words("english"))

# Step 4: Remove stop words
filtered_words = [
    word for word in words
    if word not in stop_words
]

print("Original tokens:", words)
print("After stop words removal:", filtered_words)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


Original tokens: ['i', 'love', 'learning', 'nlp', 'because', 'it', 'is', 'very', 'interesting']
After stop words removal: ['love', 'learning', 'nlp', 'interesting']


[nltk_data]   Package punkt_tab is already up-to-date!


# DAY-4

Stemming

In [2]:
import nltk
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

words = ["playing", "played", "plays", "player"]

for word in words:
    print(word, "→", stemmer.stem(word))

playing → play
played → play
plays → play
player → player


Lemmatization

In [3]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")#Open Multilingual WordNet

lemmatizer = WordNetLemmatizer()

words = ["playing", "played", "children", "cars"]

for word in words:
    print(word, "→", lemmatizer.lemmatize(word))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


playing → playing
played → played
children → child
cars → car


In [5]:
texts = [
    "Win a free prize now",
    "Meeting is at 10 AM",
    "Congratulations you won money"
]

labels = [
    "Spam",
    "Not Spam",
    "Spam"
]

for text, label in zip(texts, labels):
    print(text, "→", label)

Win a free prize now → Spam
Meeting is at 10 AM → Not Spam
Congratulations you won money → Spam


In [6]:
positive_words = ["good", "great", "love", "amazing", "excellent"]
negative_words = ["bad", "hate", "worst", "terrible", "poor"]

text = "I love this movie"

words = text.lower().split()

positive_count = sum(word in positive_words for word in words)
negative_count = sum(word in negative_words for word in words)

if positive_count > negative_count:
    sentiment = "Positive"
elif negative_count > positive_count:
    sentiment = "Negative"
else:
    sentiment = "Neutral"

print("Text:", text)
print("Sentiment:", sentiment)

Text: I love this movie
Sentiment: Positive


TF-IDF(it will give the importance to the Score)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer#text ->numerical values

texts = [
    "I love this movie",
    "This movie is amazing",
    "I hate this movie"
]

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(texts)#fit for learing/ transform for converting text to numerical values

print("Words:")
print(vectorizer.get_feature_names_out())

print("\nTF-IDF values:")
print(tfidf_matrix.toarray())

Words:
['amazing' 'hate' 'is' 'love' 'movie' 'this']

TF-IDF values:
[[0.         0.         0.         0.76749457 0.45329466 0.45329466]
 [0.6088451  0.         0.6088451  0.         0.35959372 0.35959372]
 [0.         0.76749457 0.         0.         0.45329466 0.45329466]]


In [8]:
from sklearn.model_selection import train_test_split

X = ["I love this movie",
     "This movie is amazing",
     "I hate this movie",
     "This movie is terrible"]

y = ["Positive",
     "Positive",
     "Negative",
     "Negative"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

print("Training:", X_train)
print("Testing:", X_test)

Training: ['This movie is terrible', 'I love this movie', 'I hate this movie']
Testing: ['This movie is amazing']


Text Classification

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [14]:
model.fit(X_train_tfidf, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [13]:
X_train_tfidf = vectorizer.transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training TF-IDF:", X_train_tfidf.shape)
print("Testing TF-IDF:", X_test_tfidf.shape)

Training TF-IDF: (3, 6)
Testing TF-IDF: (1, 6)


In [15]:
predictions = model.predict(X_test_tfidf)

print("Predicted:", predictions)
print("Actual:", y_test)

Predicted: ['Negative']
Actual: ['Positive']


In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 0.0


In [19]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predictions)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[0 0]
 [1 0]]
